# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

total = 0


def func(x):
    x = 1
    y = 1
    while x < 4000000:
        if y%2 ==0:
            total + y
        y = x + y
        x = func(x) + y
    print(total)



# def func():
#     n = 0
#     x = 1
#     y = 1
#     while n < 4000000:
#         n = x + y
#         if n%2 ==0:
#             total + n
#         x = y + n
#         y = x + n
#     print(total)


func(4000000)
